# Form implementation generated from reading ui file 'c:\Proyecto de Ingeria de software\abrir_mesa.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 250)
        MainWindow.setMaximumSize(QtCore.QSize(400, 250))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(550, 500))
        self.frame.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.bt_abrir = QtWidgets.QPushButton(parent=self.frame)
        self.bt_abrir.setGeometry(QtCore.QRect(40, 50, 71, 70))
        self.bt_abrir.setMaximumSize(QtCore.QSize(75, 70))
        self.bt_abrir.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 217, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 900 italic 12pt \"Segoe UI\";")
        self.bt_abrir.setObjectName("bt_abrir")
        self.bt_reservar = QtWidgets.QPushButton(parent=self.frame)
        self.bt_reservar.setGeometry(QtCore.QRect(150, 50, 75, 70))
        self.bt_reservar.setMaximumSize(QtCore.QSize(75, 70))
        self.bt_reservar.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(127, 127, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 900 italic 12pt \"Segoe UI\";")
        self.bt_reservar.setObjectName("bt_reservar")
        self.bt_cancelar = QtWidgets.QPushButton(parent=self.frame)
        self.bt_cancelar.setGeometry(QtCore.QRect(260, 50, 75, 70))
        self.bt_cancelar.setMaximumSize(QtCore.QSize(75, 70))
        self.bt_cancelar.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 55, 55, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 900 italic 12pt \"Segoe UI\";")
        self.bt_cancelar.setObjectName("bt_cancelar")
        self.lb_mesa = QtWidgets.QLabel(parent=self.frame)
        self.lb_mesa.setGeometry(QtCore.QRect(40, 20, 81, 16))
        self.lb_mesa.setStyleSheet("font: 900 italic 11pt \"Segoe UI\";")
        self.lb_mesa.setText("")
        self.lb_mesa.setObjectName("lb_mesa")
        self.bt_agregar_productos = QtWidgets.QPushButton(parent=self.frame)
        self.bt_agregar_productos.setGeometry(QtCore.QRect(80, 150, 85, 71))
        self.bt_agregar_productos.setMaximumSize(QtCore.QSize(85, 80))
        self.bt_agregar_productos.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 217, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 900 italic 12pt \"Segoe UI\";")
        self.bt_agregar_productos.setObjectName("bt_agregar_productos")
        self.bt_imprimir_cuenta = QtWidgets.QPushButton(parent=self.frame)
        self.bt_imprimir_cuenta.setGeometry(QtCore.QRect(220, 150, 80, 70))
        self.bt_imprimir_cuenta.setMaximumSize(QtCore.QSize(80, 70))
        self.bt_imprimir_cuenta.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(85, 170, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 900 italic 12pt \"Segoe UI\";")
        self.bt_imprimir_cuenta.setObjectName("bt_imprimir_cuenta")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_abrir.setText(_translate("MainWindow", "Abrir\n"
" mesa"))
        self.bt_reservar.setText(_translate("MainWindow", "Reservar"))
        self.bt_cancelar.setText(_translate("MainWindow", "Cancelar"))
        self.bt_agregar_productos.setText(_translate("MainWindow", "Agregar\n"
" Productos"))
        self.bt_imprimir_cuenta.setText(_translate("MainWindow", "Imprimir\n"
" Cuenta "))
