# Form implementation generated from reading ui file 'c:\Proyecto de Ingeria de software\login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(662, 570)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("\n"
"QFrame{\n"
"\n"
"border-radius: 20px;\n"
"background-image: url(C:/Users/eduar/OneDrive/Escritorio/iconos interfaz/cafeteria.jpg);\n"
" }\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_superior = QtWidgets.QFrame(parent=self.frame)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_superior.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"}\n"
"")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(424, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.bt_minimizar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_minimizar.setMinimumSize(QtCore.QSize(38, 38))
        self.bt_minimizar.setMaximumSize(QtCore.QSize(38, 38))
        self.bt_minimizar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Proyecto de Ingeria de software\\../Users/eduar/OneDrive/Escritorio/iconos interfaz/minimizar-signo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_minimizar.setIcon(icon)
        self.bt_minimizar.setIconSize(QtCore.QSize(20, 20))
        self.bt_minimizar.setObjectName("bt_minimizar")
        self.horizontalLayout_3.addWidget(self.bt_minimizar)
        self.bt_maximizar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_maximizar.setMinimumSize(QtCore.QSize(38, 38))
        self.bt_maximizar.setMaximumSize(QtCore.QSize(38, 38))
        self.bt_maximizar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Proyecto de Ingeria de software\\../Users/eduar/OneDrive/Escritorio/iconos interfaz/chevron-doble-up.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_maximizar.setIcon(icon1)
        self.bt_maximizar.setIconSize(QtCore.QSize(20, 20))
        self.bt_maximizar.setObjectName("bt_maximizar")
        self.horizontalLayout_3.addWidget(self.bt_maximizar)
        self.bt_normal = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_normal.setMinimumSize(QtCore.QSize(38, 38))
        self.bt_normal.setMaximumSize(QtCore.QSize(38, 38))
        self.bt_normal.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Proyecto de Ingeria de software\\../Users/eduar/OneDrive/Escritorio/iconos interfaz/chevron-doble-abajo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_normal.setIcon(icon2)
        self.bt_normal.setIconSize(QtCore.QSize(20, 20))
        self.bt_normal.setObjectName("bt_normal")
        self.horizontalLayout_3.addWidget(self.bt_normal)
        self.bt_cerrar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_cerrar.setMinimumSize(QtCore.QSize(38, 38))
        self.bt_cerrar.setMaximumSize(QtCore.QSize(38, 38))
        self.bt_cerrar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Proyecto de Ingeria de software\\../Users/eduar/OneDrive/Escritorio/iconos interfaz/x.svg.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_cerrar.setIcon(icon3)
        self.bt_cerrar.setIconSize(QtCore.QSize(20, 20))
        self.bt_cerrar.setObjectName("bt_cerrar")
        self.horizontalLayout_3.addWidget(self.bt_cerrar)
        self.verticalLayout.addWidget(self.frame_superior)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(162, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_4.setMaximumSize(QtCore.QSize(400, 600))
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.frame_4)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setStyleSheet("font: 900 20pt \"Segoe UI\";\n"
"color: black;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_2.setStyleSheet("border-radius: 10px;\n"
"font: 900 italic 20pt \"Segoe UI\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEdit1 = QtWidgets.QLineEdit(parent=self.frame_4)
        self.lineEdit1.setStyleSheet("border-radius:5px;")
        self.lineEdit1.setObjectName("lineEdit1")
        self.verticalLayout_2.addWidget(self.lineEdit1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.label_3 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_3.setStyleSheet("font: 900 italic 20pt \"Segoe UI\";\n"
"border-radius: 10px;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lineEdit2 = QtWidgets.QLineEdit(parent=self.frame_4)
        self.lineEdit2.setStyleSheet("border-radius:5px;")
        self.lineEdit2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit2.setObjectName("lineEdit2")
        self.verticalLayout_2.addWidget(self.lineEdit2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton.setStyleSheet("font: 900 italic 13pt \"Segoe UI\";\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(129, 65, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:10px;")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(162, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Py Restaurant"))
        self.label_2.setText(_translate("MainWindow", "Usuario"))
        self.label_3.setText(_translate("MainWindow", "Contraseña"))
        self.pushButton.setText(_translate("MainWindow", "Ingresar"))
