# Form implementation generated from reading ui file 'c:\Proyecto de Ingeria de software\menu_platillos.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(743, 521)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.listWidget = QtWidgets.QListWidget(parent=self.frame_2)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_6.addWidget(self.listWidget)
        self.bt_mandar_orden = QtWidgets.QPushButton(parent=self.frame_2)
        self.bt_mandar_orden.setObjectName("bt_mandar_orden")
        self.verticalLayout_6.addWidget(self.bt_mandar_orden)
        self.bt_eliminar_producto = QtWidgets.QPushButton(parent=self.frame_2)
        self.bt_eliminar_producto.setObjectName("bt_eliminar_producto")
        self.verticalLayout_6.addWidget(self.bt_eliminar_producto)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setSpacing(9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolBox = QtWidgets.QToolBox(parent=self.frame_5)
        self.toolBox.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.toolBox.setObjectName("toolBox")
        self.pg_platillos = QtWidgets.QWidget()
        self.pg_platillos.setGeometry(QtCore.QRect(0, 0, 500, 415))
        self.pg_platillos.setObjectName("pg_platillos")
        self.toolBox.addItem(self.pg_platillos, "")
        self.pg_bebidas = QtWidgets.QWidget()
        self.pg_bebidas.setGeometry(QtCore.QRect(0, 0, 500, 415))
        self.pg_bebidas.setObjectName("pg_bebidas")
        self.toolBox.addItem(self.pg_bebidas, "")
        self.verticalLayout_3.addWidget(self.toolBox)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_mandar_orden.setText(_translate("MainWindow", "Aceptar"))
        self.bt_eliminar_producto.setText(_translate("MainWindow", "Eliminar producto"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pg_platillos), _translate("MainWindow", "Platillos "))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pg_bebidas), _translate("MainWindow", "Bebidas"))
